import React from 'react'

const BlogPage = () => {
  return (
    <div className = "container">
        <h1>ブログ</h1>

        <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec eros ut justo rutrum tristique. Quisque sit amet enim nec magna mollis consectetur. Fusce id ipsum sed eros volutpat sodales. Integer varius sapien a ipsum luctus, nec fringilla dui fermentum. Nunc ultricies, neque ut scelerisque tincidunt, sapien risus ultrices nulla, vel ultricies velit metus eu mauris. Ut consequat vitae augue nec viverra. Nulla eget tellus et risus tincidunt varius. Nam porttitor pharetra velit, at auctor nulla faucibus ac. Sed pretium tellus sit amet odio posuere, ac hendrerit turpis lacinia. Maecenas nec mi ac est ultrices egestas. Nullam sit amet nunc et nisl sodales eleifend. Integer id sem in magna tempor fermentum. Aliquam erat volutpat. Integer sit amet ante libero. Integer tincidunt eros non mi tristique, vel facilisis purus aliquet.

Nam auctor, tortor sit amet fringilla eleifend, nulla quam varius nulla, et vehicula velit mi a quam. Sed nec pharetra mauris. Ut sollicitudin lacinia erat, at posuere ligula posuere nec. Maecenas consectetur quam sit amet libero placerat, eget varius enim congue. Pellentesque luctus velit id dolor finibus, et aliquet orci ultricies. Sed ac fringilla neque. In hac habitasse platea dictumst. Fusce volutpat tortor vitae massa efficitur bibendum. Curabitur luctus metus a purus lacinia, vel sollicitudin purus blandit. Donec feugiat felis nec mauris pharetra feugiat. Phasellus eleifend nisl id malesuada tempus.

Duis vehicula ante eget urna volutpat laoreet. Maecenas venenatis nisl eget fringilla tincidunt. Mauris non arcu vel nunc congue aliquam. Proin mattis tellus id arcu posuere congue. Duis sollicitudin felis id purus dapibus, eget rhoncus nulla fermentum. Aenean id arcu ac urna tempor vehicula id ut orci. Cras pretium ex a lacus lacinia, sit amet condimentum ex mattis. Phasellus nec justo ullamcorper, venenatis sem at, condimentum mauris. Nulla facilisi. Sed semper risus vel purus sodales, non malesuada felis ultrices. Donec malesuada quam et erat ultrices tincidunt. Vivamus vehicula lacus at enim ultrices, a aliquam dolor vulputate. Phasellus feugiat ligula nec arcu posuere, at ultricies nulla consequat. Suspendisse potenti. Nulla facilisi. Sed non enim quis felis interdum rutrum. Sed in est eu sapien faucibus sodales. Sed nec odio sed risus aliquet convallis eget vitae risus.

Vivamus lacinia quam ut tellus accumsan, eget dictum libero consequat. Vestibulum convallis felis eu magna tempus suscipit. Mauris auctor lacus non nibh feugiat sodales. Fusce sodales, justo a viverra dapibus, ipsum justo convallis elit, ac ultricies orci sapien eget nisi. Aliquam nec massa nec ligula vestibulum consectetur. Ut rhoncus nibh in justo lobortis bibendum. Suspendisse potenti. Phasellus sed enim sit amet quam efficitur tempus. Maecenas non vehicula purus. Suspendisse potenti. Nullam tempor, felis eget consectetur consectetur, velit lorem laoreet purus, eget venenatis elit orci nec lorem. Sed lobortis nunc nec nisl efficitur, a ultricies tortor convallis. Vivamus maximus eros in metus vestibulum, vel vehicula lorem sagittis. Nullam tristique tincidunt odio vitae vestibulum. Maecenas non odio ac arcu gravida interdum. Sed at turpis id lacus aliquam malesuada. Phasellus accumsan dapibus odio, nec commodo est vehicula vitae. Sed finibus urna non fermentum convallis.
        </p>
        <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec eros ut justo rutrum tristique. Quisque sit amet enim nec magna mollis consectetur. Fusce id ipsum sed eros volutpat sodales. Integer varius sapien a ipsum luctus, nec fringilla dui fermentum. Nunc ultricies, neque ut scelerisque tincidunt, sapien risus ultrices nulla, vel ultricies velit metus eu mauris. Ut consequat vitae augue nec viverra. Nulla eget tellus et risus tincidunt varius. Nam porttitor pharetra velit, at auctor nulla faucibus ac. Sed pretium tellus sit amet odio posuere, ac hendrerit turpis lacinia. Maecenas nec mi ac est ultrices egestas. Nullam sit amet nunc et nisl sodales eleifend. Integer id sem in magna tempor fermentum. Aliquam erat volutpat. Integer sit amet ante libero. Integer tincidunt eros non mi tristique, vel facilisis purus aliquet.

Nam auctor, tortor sit amet fringilla eleifend, nulla quam varius nulla, et vehicula velit mi a quam. Sed nec pharetra mauris. Ut sollicitudin lacinia erat, at posuere ligula posuere nec. Maecenas consectetur quam sit amet libero placerat, eget varius enim congue. Pellentesque luctus velit id dolor finibus, et aliquet orci ultricies. Sed ac fringilla neque. In hac habitasse platea dictumst. Fusce volutpat tortor vitae massa efficitur bibendum. Curabitur luctus metus a purus lacinia, vel sollicitudin purus blandit. Donec feugiat felis nec mauris pharetra feugiat. Phasellus eleifend nisl id malesuada tempus.

Duis vehicula ante eget urna volutpat laoreet. Maecenas venenatis nisl eget fringilla tincidunt. Mauris non arcu vel nunc congue aliquam. Proin mattis tellus id arcu posuere congue. Duis sollicitudin felis id purus dapibus, eget rhoncus nulla fermentum. Aenean id arcu ac urna tempor vehicula id ut orci. Cras pretium ex a lacus lacinia, sit amet condimentum ex mattis. Phasellus nec justo ullamcorper, venenatis sem at, condimentum mauris. Nulla facilisi. Sed semper risus vel purus sodales, non malesuada felis ultrices. Donec malesuada quam et erat ultrices tincidunt. Vivamus vehicula lacus at enim ultrices, a aliquam dolor vulputate. Phasellus feugiat ligula nec arcu posuere, at ultricies nulla consequat. Suspendisse potenti. Nulla facilisi. Sed non enim quis felis interdum rutrum. Sed in est eu sapien faucibus sodales. Sed nec odio sed risus aliquet convallis eget vitae risus.

Vivamus lacinia quam ut tellus accumsan, eget dictum libero consequat. Vestibulum convallis felis eu magna tempus suscipit. Mauris auctor lacus non nibh feugiat sodales. Fusce sodales, justo a viverra dapibus, ipsum justo convallis elit, ac ultricies orci sapien eget nisi. Aliquam nec massa nec ligula vestibulum consectetur. Ut rhoncus nibh in justo lobortis bibendum. Suspendisse potenti. Phasellus sed enim sit amet quam efficitur tempus. Maecenas non vehicula purus. Suspendisse potenti. Nullam tempor, felis eget consectetur consectetur, velit lorem laoreet purus, eget venenatis elit orci nec lorem. Sed lobortis nunc nec nisl efficitur, a ultricies tortor convallis. Vivamus maximus eros in metus vestibulum, vel vehicula lorem sagittis. Nullam tristique tincidunt odio vitae vestibulum. Maecenas non odio ac arcu gravida interdum. Sed at turpis id lacus aliquam malesuada. Phasellus accumsan dapibus odio, nec commodo est vehicula vitae. Sed finibus urna non fermentum convallis.
        </p>
        <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec eros ut justo rutrum tristique. Quisque sit amet enim nec magna mollis consectetur. Fusce id ipsum sed eros volutpat sodales. Integer varius sapien a ipsum luctus, nec fringilla dui fermentum. Nunc ultricies, neque ut scelerisque tincidunt, sapien risus ultrices nulla, vel ultricies velit metus eu mauris. Ut consequat vitae augue nec viverra. Nulla eget tellus et risus tincidunt varius. Nam porttitor pharetra velit, at auctor nulla faucibus ac. Sed pretium tellus sit amet odio posuere, ac hendrerit turpis lacinia. Maecenas nec mi ac est ultrices egestas. Nullam sit amet nunc et nisl sodales eleifend. Integer id sem in magna tempor fermentum. Aliquam erat volutpat. Integer sit amet ante libero. Integer tincidunt eros non mi tristique, vel facilisis purus aliquet.

Nam auctor, tortor sit amet fringilla eleifend, nulla quam varius nulla, et vehicula velit mi a quam. Sed nec pharetra mauris. Ut sollicitudin lacinia erat, at posuere ligula posuere nec. Maecenas consectetur quam sit amet libero placerat, eget varius enim congue. Pellentesque luctus velit id dolor finibus, et aliquet orci ultricies. Sed ac fringilla neque. In hac habitasse platea dictumst. Fusce volutpat tortor vitae massa efficitur bibendum. Curabitur luctus metus a purus lacinia, vel sollicitudin purus blandit. Donec feugiat felis nec mauris pharetra feugiat. Phasellus eleifend nisl id malesuada tempus.

Duis vehicula ante eget urna volutpat laoreet. Maecenas venenatis nisl eget fringilla tincidunt. Mauris non arcu vel nunc congue aliquam. Proin mattis tellus id arcu posuere congue. Duis sollicitudin felis id purus dapibus, eget rhoncus nulla fermentum. Aenean id arcu ac urna tempor vehicula id ut orci. Cras pretium ex a lacus lacinia, sit amet condimentum ex mattis. Phasellus nec justo ullamcorper, venenatis sem at, condimentum mauris. Nulla facilisi. Sed semper risus vel purus sodales, non malesuada felis ultrices. Donec malesuada quam et erat ultrices tincidunt. Vivamus vehicula lacus at enim ultrices, a aliquam dolor vulputate. Phasellus feugiat ligula nec arcu posuere, at ultricies nulla consequat. Suspendisse potenti. Nulla facilisi. Sed non enim quis felis interdum rutrum. Sed in est eu sapien faucibus sodales. Sed nec odio sed risus aliquet convallis eget vitae risus.

Vivamus lacinia quam ut tellus accumsan, eget dictum libero consequat. Vestibulum convallis felis eu magna tempus suscipit. Mauris auctor lacus non nibh feugiat sodales. Fusce sodales, justo a viverra dapibus, ipsum justo convallis elit, ac ultricies orci sapien eget nisi. Aliquam nec massa nec ligula vestibulum consectetur. Ut rhoncus nibh in justo lobortis bibendum. Suspendisse potenti. Phasellus sed enim sit amet quam efficitur tempus. Maecenas non vehicula purus. Suspendisse potenti. Nullam tempor, felis eget consectetur consectetur, velit lorem laoreet purus, eget venenatis elit orci nec lorem. Sed lobortis nunc nec nisl efficitur, a ultricies tortor convallis. Vivamus maximus eros in metus vestibulum, vel vehicula lorem sagittis. Nullam tristique tincidunt odio vitae vestibulum. Maecenas non odio ac arcu gravida interdum. Sed at turpis id lacus aliquam malesuada. Phasellus accumsan dapibus odio, nec commodo est vehicula vitae. Sed finibus urna non fermentum convallis.
        </p>
        <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec eros ut justo rutrum tristique. Quisque sit amet enim nec magna mollis consectetur. Fusce id ipsum sed eros volutpat sodales. Integer varius sapien a ipsum luctus, nec fringilla dui fermentum. Nunc ultricies, neque ut scelerisque tincidunt, sapien risus ultrices nulla, vel ultricies velit metus eu mauris. Ut consequat vitae augue nec viverra. Nulla eget tellus et risus tincidunt varius. Nam porttitor pharetra velit, at auctor nulla faucibus ac. Sed pretium tellus sit amet odio posuere, ac hendrerit turpis lacinia. Maecenas nec mi ac est ultrices egestas. Nullam sit amet nunc et nisl sodales eleifend. Integer id sem in magna tempor fermentum. Aliquam erat volutpat. Integer sit amet ante libero. Integer tincidunt eros non mi tristique, vel facilisis purus aliquet.

Nam auctor, tortor sit amet fringilla eleifend, nulla quam varius nulla, et vehicula velit mi a quam. Sed nec pharetra mauris. Ut sollicitudin lacinia erat, at posuere ligula posuere nec. Maecenas consectetur quam sit amet libero placerat, eget varius enim congue. Pellentesque luctus velit id dolor finibus, et aliquet orci ultricies. Sed ac fringilla neque. In hac habitasse platea dictumst. Fusce volutpat tortor vitae massa efficitur bibendum. Curabitur luctus metus a purus lacinia, vel sollicitudin purus blandit. Donec feugiat felis nec mauris pharetra feugiat. Phasellus eleifend nisl id malesuada tempus.

Duis vehicula ante eget urna volutpat laoreet. Maecenas venenatis nisl eget fringilla tincidunt. Mauris non arcu vel nunc congue aliquam. Proin mattis tellus id arcu posuere congue. Duis sollicitudin felis id purus dapibus, eget rhoncus nulla fermentum. Aenean id arcu ac urna tempor vehicula id ut orci. Cras pretium ex a lacus lacinia, sit amet condimentum ex mattis. Phasellus nec justo ullamcorper, venenatis sem at, condimentum mauris. Nulla facilisi. Sed semper risus vel purus sodales, non malesuada felis ultrices. Donec malesuada quam et erat ultrices tincidunt. Vivamus vehicula lacus at enim ultrices, a aliquam dolor vulputate. Phasellus feugiat ligula nec arcu posuere, at ultricies nulla consequat. Suspendisse potenti. Nulla facilisi. Sed non enim quis felis interdum rutrum. Sed in est eu sapien faucibus sodales. Sed nec odio sed risus aliquet convallis eget vitae risus.

Vivamus lacinia quam ut tellus accumsan, eget dictum libero consequat. Vestibulum convallis felis eu magna tempus suscipit. Mauris auctor lacus non nibh feugiat sodales. Fusce sodales, justo a viverra dapibus, ipsum justo convallis elit, ac ultricies orci sapien eget nisi. Aliquam nec massa nec ligula vestibulum consectetur. Ut rhoncus nibh in justo lobortis bibendum. Suspendisse potenti. Phasellus sed enim sit amet quam efficitur tempus. Maecenas non vehicula purus. Suspendisse potenti. Nullam tempor, felis eget consectetur consectetur, velit lorem laoreet purus, eget venenatis elit orci nec lorem. Sed lobortis nunc nec nisl efficitur, a ultricies tortor convallis. Vivamus maximus eros in metus vestibulum, vel vehicula lorem sagittis. Nullam tristique tincidunt odio vitae vestibulum. Maecenas non odio ac arcu gravida interdum. Sed at turpis id lacus aliquam malesuada. Phasellus accumsan dapibus odio, nec commodo est vehicula vitae. Sed finibus urna non fermentum convallis.
        </p>
    </div>
  )
}

export default BlogPage